# Generated by Django 5.1.3 on 2024-11-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_kicd_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kicd_number',
            field=models.CharField(blank=True, help_text=" User's kicd number", max_length=50),
        ),
    ]
